name: CI-test

on:
  push:
    branches: 
      - testBridge

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: testBridge
        fetch-depth: 0
        lfs: true

    # - name: Set git identity
    #   run : |
    #     git config --global user.email "KFER.Mercer@gmail.com"
    #     git config --global user.name "KFERMercer"

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: files
        path: /etc/apt/

    # - name: Prepare
    #   run: |
    #       # modify apt mirrors
    #       sudo cat > /etc/apt/sources.list <<EOF
    #       deb http://archive.ubuntu.com/ubuntu/ boinc main restricted universe multiverse
    #       # deb-src http://archive.ubuntu.com/ubuntu/ boinc main restricted universe multiverse

    #       deb http://archive.ubuntu.com/ubuntu/ boinc-security main restricted universe multiverse
    #       # deb-src http://archive.ubuntu.com/ubuntu/ boinc-security main restricted universe multiverse

    #       deb http://archive.ubuntu.com/ubuntu/ boinc-updates main restricted universe multiverse
    #       # deb-src http://archive.ubuntu.com/ubuntu/ boinc-updates main restricted universe multiverse

    #       # deb http://archive.ubuntu.com/ubuntu/ boinc-proposed main restricted universe multiverse
    #       # deb-src http://archive.ubuntu.com/ubuntu/ boinc-proposed main restricted universe multiverse

    #       deb http://archive.ubuntu.com/ubuntu/ boinc-backports main restricted universe multiverse
    #       # deb-src http://archive.ubuntu.com/ubuntu/ boinc-backports main restricted universe multiverse
    #       EOF
    #       cat /etc/apt/sources.list
