name: CI-test

on:
  push:
    branches: 
      - testBridge

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: testBridge
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "KFER.Mercer@gmail.com"
        git config --global user.name "KFERMercer"

    - name: Load upstream commits
      run: git pull https://github.com/KFERMercer/OpenWrt-CI.git --no-edit --allow-unrelated-histories --strategy-option ours

    - name: Push Commits
      run: git push origin testBridge
