name: CI-test

on:
  push:
    branches: 
      - testBridge

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: testBridge
        fetch-depth: 0
        lfs: true

    # - name: Set git identity
    #   run : |
    #     git config --global user.email "KFER.Mercer@gmail.com"
    #     git config --global user.name "KFERMercer"

    - name: Prepare
      run: |
        cat /etc/apt/sources.list
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./
        du -h --max-depth=1 ./.git

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: files
        path: /etc/apt/
