name: CI-test

on:
  push:
    branches: 
      - testBridge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: testBridge

      - name: Tset
        run: |
          touch ./test-file
          cat >> ./test-file <<EOF
          line 1
          line 2
          line 3
          # line 4
          EOF

          cat >> ./test-file <<EOF
          line 5
          line 6
          # line 7
          # line 8
          EOF

      - name : Upload artifact
        run : scho 111111 >> ./test-file
        uses: actions/upload-artifact@master
        with:
          name: test-file
          path: test-file
